### ISSUE TITLE
GitHub Workflow, `publish-to-npm` failing

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/wds#70]
### 💡 Description

The `publish-to-npm` GitHub Workflow failed after creating our initial release with the error:

```console
...
npm error code ENEEDAUTH
npm error need auth This command requires you to be logged in to https://registry.npmjs.org/
npm error need auth You need to authorize this machine using `npm adduser`
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-10-23T16_45_32_244Z-debug-0.log
Error: Process completed with exit code 1.
```

Full execution log: https://github.com/NASA-PDS/wds/actions/runs/11484423314/job/31962160635#step:7:131

**Comment by anilnatha** [comment]
I updated the publish to npm workflow where I updated the NPMJS Token variable name to match what we have stored in our GH Org's secrets. I created a "dev" release against my working branch to test it. The fix appears to have fixed the issue reported in this ticket; however, we're now experiencing a new issue 

```
...
npm error code E404
npm error 404 Not Found - PUT https://registry.npmjs.org/@nasapds%2fwds - Not found
npm error 404
npm error 404  '@nasapds/wds@0.0.1' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-10-30T21_10_50_940Z-debug-0.log
Error: Process completed with exit code 1.
```

Reference GitHub Action Execution Log:  https://github.com/NASA-PDS/wds/actions/runs/11601706554/job/32305071426#step:7:135

I will continue to investigate the issue.

**Comment by tloubrieu-jpl** [comment]
@anilnatha is still working on that 404 error.

**Comment by tloubrieu-jpl** [comment]
The tokens were outdated. This is fixed, see PR
